

export const RECIPE_REQUEST_PENDING = 'RECIPE.RECIPE_REQUEST_PENDING';
export const RECIPE_REQUEST_SUCCESS = 'RECIPE.RECIPE_REQUEST_SUCCESS';
export const RECIPE_REQUEST_FAILED = 'RECIPE.RECIPE_REQUEST_FAILED';