

export const RECIPE_REQUEST_PENDING = 'RECIPE.RECIPE_REQUEST_PENDING';
export const RECIPE_REQUEST_SUCCESS = 'RECIPE.RECIPE_REQUEST_SUCCESS';
export const RECIPE_REQUEST_FAILED = 'RECIPE.RECIPE_REQUEST_FAILED';

export const CURRENT_RECIPE_REQUEST_PENDING = 'CURRENT_RECIPE.RECIPE_REQUEST_PENDING';
export const CURRENT_RECIPE_REQUEST_SUCCESS = 'CURRENT_RECIPE.RECIPE_REQUEST_SUCCESS';
export const CURRENT_RECIPE_REQUEST_FAILED = 'CURRENT_RECIPE.RECIPE_REQUEST_FAILED';

