export const ALL_TODOS_REQUEST_PENDING = 'ALL_TODOS_REQUEST_PENDING';
export const ALL_TODOS_REQUEST_SUCCESS = 'ALL_TODOS_REQUEST_SUCCESS';
export const ALL_TODOS_REQUEST_FAILED = 'ALL_TODOS_REQUEST_FAILED';

export const MARK_TODO_REQUEST_PENDING = 'MARK_TODO_REQUEST_PENDING';
export const MARK_TODO_REQUEST_SUCCESS = 'MARK_TODO_REQUEST_SUCCESS';
export const MARK_TODO_REQUEST_FAILED = 'MARK_TODO_REQUEST_FAILED';
