export const ALL_TODOS_REQUEST_PENDING = 'ALL_TODOS_REQUEST_PENDING';
export const ALL_TODOS_REQUEST_SUCCESS = 'ALL_TODOS_REQUEST_SUCCESS';
export const ALL_TODOS_REQUEST_FAILED = 'ALL_TODOS_REQUEST_FAILED';
