export const RECIPE_REQUEST_PENDING = 'RECIPE_REQUEST_PENDING';
export const RECIPE_REQUEST_SUCCESS = 'RECIPE_REQUEST_SUCCESS';
export const RECIPE_REQUEST_FAILED = 'RECIPE_REQUEST_FAILED';

/*display constants*/
export const SHOW_PAGE = 'SHOW_PAGE';